# Generated by Django 4.2.6 on 2024-09-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='status',
            field=models.CharField(default='waiting', max_length=50),
        ),
    ]
