# Generated by Django 4.2.6 on 2024-09-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tguser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='last_message',
            field=models.TextField(blank=True),
        ),
    ]
