# Generated by Django 5.0 on 2024-09-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_adminonlineorofflinecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_busy',
        ),
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Boshqasi bilan gaplashvoti')], default='offline', max_length=10),
        ),
        migrations.DeleteModel(
            name='AdminOnlineOrOfflineCheck',
        ),
    ]
